on:
  push:
    paths:
      - .github/workflows/v1.yaml
      - v1/**/*

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@main
      - run: python v1/a/folder/with/a/file.py
