on:
  push:
    paths:
      - .github/workflows/v2.yaml
      - v2/**/*

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@main
      - run: pip install -r v2/a/second/frontend/requirements.txt
      - run: python v2/a/second/frontend/appeared.py
